import { type AppType } from "next/app";
import { api } from "~/utils/api";
import { ClerkProvider, SignedIn, SignedOut } from "@clerk/nextjs";
import Head from "next/head";
import SignInPage from "~/components/signinpage";
import Sidebar from "~/components/sidebar";
import "~/styles/globals.css";

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <title>Wuju</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/wuju-logo.ico" />
      </Head>
      <ClerkProvider {...pageProps}>
        <SignedIn>
          <Component {...pageProps} />
          <Sidebar />
        </SignedIn>
        <SignedOut>
          <SignInPage />
        </SignedOut>
      </ClerkProvider>
    </>
  );
};

export default api.withTRPC(MyApp);
