import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Wuju</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/wuju-logo.ico" />
      </Head>
      <main className="flex h-screen w-full items-center justify-center md:bg-off-white">
        <div className="flex h-[40rem] w-full max-w-sm flex-col items-center justify-center rounded-2xl bg-white text-center md:shadow-lg">
          <Image
            src="/wuju-logo.png"
            alt="main-logo"
            width={75}
            height={75}
            className="mx-auto"
          />
          <h1 className="mb-6 font-dmsans text-6xl">Wuju</h1>
          <p className="mb-20 text-sm">Track all your expenses easily.</p>
          <button className="w-64 rounded-full bg-main-black p-3 font-semibold text-white">
            Sign in
          </button>
        </div>
      </main>
    </>
  );
};

export default Home;
